import Navbar from "@/src/components/Navbar";
import "./globals.css";
import { Inter, Cinzel } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inter",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-cinzel",
});

export const metadata = {
  title: "Lula de Oro | Fotografia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${inter.variable} ${cinzel.variable}`}>
      <body>
          <Navbar />
        {children}
      </body>
    </html>
  );
}
